### PR TITLE
Fix/lint 100

### PR DESCRIPTION
**Pull request by widhalmt**
Several linter findings fixed.

### CODE REVIEW

**Comment by widhalmt** [comment]
Needs #47 to be merged before all tests can work.

**Comment by widhalmt** [comment]
Needs #52 to be merged before all checks can run through.

**Comment by widhalmt** [comment]
Needs #53 to be merged before it will work

**Comment by widhalmt** [comment]
Needs #54 to be fixed to work

**Review by afeefghannam89 — DISMISSED** [review]

**Pull request merged**
