### PR TITLE
Configure Galaxy in Molecule

### LINKED ISSUE #254: Parts of requirements files are ignored
By accident I found the following message in a jobs output:

```
  [WARNING]: The requirements file '/home/runner/work/ansible-collection-
  elasticstack/ansible-collection-
  elasticstack/molecule/elasticstack_default/requirements.yml' contains
  collections which will be ignored. To install these collections run 'ansible-
  galaxy collection install -r' or to install both at the same time run 'ansible-
  galaxy install -r' without a custom install path.
```

I'll look into it.

### PR DESCRIPTION
**Pull request by widhalmt**
This will force Molecule to run Ansible Galaxy twice. Once for roles, once for collection.

fixes #254

### CODE REVIEW

**Comment by widhalmt** [comment]
I'm not convinced that this change is really neccessary. It seems like the behaviour is exactly the same. My interpretation for now: First it installs the collections, then it runs again for roles. Since the both runs don't know of each other, the second issues the warning. So, since it's working as expected I'm ok with both - merging or closing.

Tests seem to fail because of timeouts at Rocky Linux repos.

**Comment by afeefghannam89** [comment]
@widhalmt where is the collections.yml file, I do not see it? Did I misunderstand the goal of this PR? Can you please clarify more?

**Comment by widhalmt** [comment]
Of course. I got the name wrong. 🤦🏽 I meant the `requirements.yml` in most Molecule scenarios.

**Review by afeefghannam89 — COMMENTED** [review]
Thanks ;)

**Review by afeefghannam89 — APPROVED** [review]

**Pull request merged**
