### PR TITLE
Enhancement pipelines

### LINKED ISSUE #180: CI/CD pull request test run while updating documentation
pull request CD/CI checks run when we update README.md or docs. We should restrict this to the concerned files/directories.

### LINKED ISSUE #189: Fix logstash pipeline
Logstash pipeline fails, because of the usage of the latest python version with molecule test.

### PR DESCRIPTION
**Pull request by afeefghannam89**
* Restrict the pull request workflow, fix #180 
* Use python 3.8 in Logstash pipeline, fix #189 
*  Only run pr workflow while opening a pull request, but not in merge queue #193 
* Merge or squeeze logstash CI/CD pipelines #172
* Fix full stack workflow on all containers #194

### CODE REVIEW

**Comment by widhalmt** [comment]
I see parallel checks. Won't that lead to collisions where different instances could run in the same container and so break a run?

**Comment by afeefghannam89** [comment]
> I see parallel checks. Won't that lead to collisions where different instances could run in the same container and so break a run?

N, I do not think so. Every instance will run separately. Did you see under the GitHub action history?

**Comment by widhalmt** [comment]
No, I didn't see it now. It just occured to me, that in some tests I had the same test breaking on different stages for no apparent reason. On closer analysis I found out that another Ansible run was changing things the current test just made. Thus it became apparent that several tests were using the same container.

But I have to admit, this happened long back and might not be an issue at all in current setups.

The easy solution, just renaming the containers in `molecule.yml` doesn't work if you run the same test with different variables from a matrix.

**Review by widhalmt — APPROVED** [review]
This will greatly improve our testing. Thank you a lot!

**Pull request merged**
