### PR TITLE
Feature/jvm options

### PR DESCRIPTION
**Pull request by ivareri**
Move custom jvm options to files in `jvm.options.d` as recommended by Elastic.  Fixes https://github.com/NETWAYS/ansible-collection-elasticstack/issues/287

I left the current default for `elasticsearch_heap` in order to avoid changing the current behaviour.  IMO this default should either be removed or set to `False`. 

I'm removed the `elasticsearch_config_jvm` variable, as any options can be overridden by using `elasticsearch_jvm_custom_parameters`. Alternatively I could add a tasks that uses this variable to install a custom `jvm.options` file, and skip the other jvm options tasks.

### CODE REVIEW

**Comment by widhalmt** [comment]
Nice, thank you for your contribution!

I'll let the automated tests run and then we'll dive into the specifics. Looking good so far.

**Comment by ivareri** [comment]
Had time to look into this one yet?

**Comment by widhalmt** [comment]
Not yet, sorry. But I try to squeeze it in this or next week.

**Comment by widhalmt** [comment]
Sorry, took me longer than I want to admit to wrap my head around some of the changes. Very elegant code, thanks.

I just merged the latest `main` and when the checks still run through, I'll merge.

**Review by widhalmt — APPROVED** [review]
Looks good to me, thanks.

**Pull request merged**
