### PR TITLE
Remove actions for pushs 

### LINKED ISSUE #302: [Bug]: Workflows triggered more than once
### Please try to fill out as much of the information below as you can. Thank you!

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Which version contains the bug?

_No response_

### Describe the bug

Currently the most workflows are triggered more than once.

### How to recreate the bug?

_No response_

### PR DESCRIPTION
**Pull request by tbauriedel**
At the moment workflows are triggered for PRs and pushs.

The workflow to contribute says that a PR must be created beforehand for each contribution into main.
For this reason (and to avoid duplicate workflows), github workflows should only be triggered for PRs.

I have also checked this branch before creating the PR. No workflow were scheduled.

Fixes #302

### CODE REVIEW

**Comment by widhalmt** [comment]
Looks good. I'll let pipelines run and check if everything works as expected. Maybe, when all succeeded we can do another push and try of they still work? The both of us are quite sure that it will work but this might still help with finding unexpected behaviour.

**Comment by tbauriedel** [comment]
I have also enabled that the linter will run **always**.

**Comment by tbauriedel** [comment]
> Looks good. I'll let pipelines run and check if everything works as expected. Maybe, when all succeeded we can do another push and try of they still work? The both of us are quite sure that it will work but this might still help with finding unexpected behaviour.

Sure. You can start one after that. 
If something is missing, I can check that again.

**Comment by widhalmt** [comment]
When everything's done, I'll just update the branch from main. We should then see if they run again. If they do, I'll approve. This should speed up checks again (by a lot)

**Comment by tbauriedel** [comment]
Works ;)

**Review by widhalmt — APPROVED** [review]
Pipelines work as expected, now. Thanks!

**Pull request merged**
